### ISSUE TITLE
QA for Front End course

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/fe-how-the-web-works#5]
references terminal and having students open up terminal when talking about IP addresses and asks students to use terminal. it's a cool little exercise but don't think we can do this with the IDE. 

(If you open the Terminal and type `ping www.facebook.com` it will respond with the following: 

``` shell
PING star-mini.c10r.facebook.com (31.13.73.36): 56 data bytes
64 bytes from 31.13.73.36: icmp_seq=0 ttl=247 time=32.776 ms.....
```

) 

cc @matbalez @jmburges

**Comment by pletcher** [comment]
We can do this with the IDE :)
